// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

import sensitiveData from "./sensitiveData";

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": sensitiveData.aws_appsync_graphqlEndpoint,
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": sensitiveData.aws_appsync_apiKey
};


export default awsmobile;
